[project]
name = "a-maze-ing"
version = "1.0.0"
description = "A maze generationa and pathfinding project done as part of 42 School's Common Core Curriculum"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mazegen",
    "mlx",
    "pillow>=12.3.0",
]

[tool.uv.sources]
mlx = { path = "lib/mlx-2.2-py3-none-any.whl" }
mazegen = { workspace = true, editable = true }

[tool.uv.workspace]
members = [
    "mazegen",
]